# Generated by Django 5.0.9 on 2024-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cofre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=254, null=True, verbose_name='Descrição')),
                ('hostname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Hostname')),
                ('ip', models.CharField(blank=True, max_length=254, null=True, verbose_name='IP')),
                ('url', models.CharField(blank=True, max_length=254, null=True, verbose_name='Url')),
                ('usuario', models.CharField(max_length=254, null=True, verbose_name='Usuário')),
                ('senha', models.CharField(help_text='Altere este campo somente se desejar alterar a senha. O campo é criptografado após salvar.', max_length=254, null=True, verbose_name='Senha')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Registro de Cofre',
                'verbose_name_plural': 'Registros de Cofre',
                'unique_together': {('descricao', 'usuario')},
            },
        ),
    ]
