# Generated by Django 5.0.9 on 2024-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofre',
            name='descricao',
            field=models.CharField(default='', max_length=254, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='obs',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='senha',
            field=models.CharField(default='', help_text='Altere este campo somente se desejar alterar a senha. O campo é criptografado após salvar.', max_length=254, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='url',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='cofre',
            name='usuario',
            field=models.CharField(default='', max_length=254, verbose_name='Usuário'),
        ),
    ]
